DRS/Models/District.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DRS.Models
{
    public class District
    {
        public District()
        {
            this.vessels = new HashSet<Vessel>();
        }
        public int district_id { get; set; }
        [Display(Name ="Reg.District Code")]
        [Required(ErrorMessage ="Vessel Reg.District Code is Required")]
        public string district_code { get; set; }
        [Display(Name = "Reg.District Name")]
        [Required(ErrorMessage ="Vessel Reg.District Name is Required")]
        public string district_name { get; set; }
        //common data
        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        public DateTime district_created_date { get; set; }
        [Display(Name = "Created By")]
        public string district_created_by { get; set; }
        [Display(Name = "Last Modified Date")]
        [DataType(DataType.Date)]
        public DateTime district_last_modified_date { get; set; }
        [Display(Name = "Last Modified By")]
        public string district_last_modified_by { get; set; }
        public int district_status { get; set; }

        public virtual ICollection<Vessel> vessels { get; set; }
    }
}

DRS/Controllers/DistrictsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using DRS.ControllerManagers.DistrictsControllerManager;
using DRS.DataBase;

namespace DRS.Controllers
{
    public class DistrictsController : Controller
    {
        private DistrictsControllerManager DistrictsControllerManager;
        public DistrictsController()
        {
            DistrictsControllerManager = new DistrictsControllerManager();
        }

        [Authorize(Roles ="Admin")]
        // GET: Districts
        public ActionResult Index()
        {
            try
            {
                // Try fetching the results from the cache
                var results = HttpContext.Cache["results"] as IEnumerable<district>;
                if (results == null)
                {
                    // the results were not found in the cache => invoke the expensive 
                    // operation to fetch them
                    results = DistrictsControllerManager.getAllDistricts();

                    // store the results into the cache so that on subsequent calls on this action
                    // the expensive operation would not be called
                    HttpContext.Cache["results"] = results;
                }

                // return the results to the view for displaying
                return View(results);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Districts/Index" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Districts/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return View(DistrictsControllerManager.getDistrict(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Districts/Details/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Districts/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Districts/Create" });
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: Districts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(district district)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = DistrictsControllerManager.saveDistrict(district);
                    if (flag == 1)
                    {
                        HttpContext.Cache.Remove("results");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["district_code"] = "This District is already taken";
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Districts/Create" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Districts/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                return View(DistrictsControllerManager.getDistrict(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Districts/Edit/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: Districts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, district district)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = DistrictsControllerManager.updateDistrict(id, district);
                    if (flag == 1)
                    {
                        HttpContext.Cache.Remove("results");
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Districts/Edit/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Districts/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                return View(DistrictsControllerManager.getDistrict(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Districts/Delete/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: Districts/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, district district)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = DistrictsControllerManager.deleteDistrict(id, district);
                    if (flag == 1)
                    {
                        HttpContext.Cache.Remove("results");
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Districts/Delete/int" });
            }
        }
    }
}

DRS/Views/Districts/Create.cshtml
@model DRS.DataBase.district

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>District</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if(TempData["district_code"] != null)
        {
            <p style="color:red">@TempData["district_code"]</p>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.district_code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.district_code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.district_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.district_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.district_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.district_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

DRS/Views/Districts/Delete.cshtml
@model DRS.DataBase.district

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>District</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.district_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_name)
        </dd>
    </dl>

    <br />
    <h4>Record Details</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.district_created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_last_modified_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_last_modified_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_last_modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_last_modified_by)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.district_id)
        @Html.HiddenFor(model => model.district_code)
        @Html.HiddenFor(model => model.district_name)
        @Html.HiddenFor(model => model.district_created_date)
        @Html.HiddenFor(model => model.district_created_by)
        @Html.HiddenFor(model => model.district_status)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

DRS/Views/Districts/Details.cshtml
@model DRS.DataBase.district

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>District</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.district_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_name)
        </dd>
    </dl>

    <br />
    <h4>Record Details.</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.district_created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_last_modified_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_last_modified_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district_last_modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district_last_modified_by)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.district_id }, htmlAttributes: new { @class = "btn btn-warning" })
</p>

DRS/Views/Districts/Edit.cshtml
@model DRS.DataBase.district

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.district_id)
    @Html.HiddenFor(model => model.district_created_date)
    @Html.HiddenFor(model => model.district_created_by)
    @Html.HiddenFor(model => model.district_status)

    <div class="form-horizontal">
        <h4>District</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.district_code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.district_code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.district_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.district_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.district_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.district_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

DRS/Views/Districts/Index.cshtml
@model IEnumerable<DRS.DataBase.district>
@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vessel Registration Districs</h2>

<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

<p>
    @Html.ActionLink("Create New", "Create", "Districts", htmlAttributes: new { @class = "btn btn-success btn-primary btn-sm" })
</p>
<div class="code-cut">
    @Html.Grid(Model).Columns(Columns =>{
    Columns.Add(c => c.district_code).Titled("District Code").Filterable(true);
    Columns.Add(c => c.district_name).Titled("District Name").Filterable(true);
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Edit", "Edit", "Districts", new { id = c.district_id }, htmlAttributes: new { @class = "btn btn-warning btn-primary btn-sm" })
        .ToHtmlString());
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Details", "Details", "Districts", new { id = c.district_id }, htmlAttributes: new { @class = "btn btn-info btn-primary btn-sm" })
        .ToHtmlString());
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Delete", "Delete", "Districts", new { id = c.district_id }, htmlAttributes: new { @class = "btn btn-warning btn-danger btn-sm" })
        .ToHtmlString());
}).WithPaging(10).Sortable().Filterable()
</div>