DRS/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DRS.Models
{
    public class Owner
    {
        public Owner()
        {
            this.vessel_owner_ref = new HashSet<VesselOwnerRef>();
        }
        public int owner_id { get; set; }
        [Display(Name = "Owner Name")]
        [Required(ErrorMessage = "Owner Name is Required")]
        public string owner_name { get; set; }
        [Display(Name = "NIC No")]
        public string owner_nic { get; set; }
        [Display(Name = "Resident Address")]
        [Required(ErrorMessage = "Address is Required")]
        public string owner_address { get; set; }
        [Display(Name = "Telephone No")]
        public string owner_tele { get; set; }
        //common data
        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        public DateTime owner_created_date { get; set; }
        [Display(Name = "Created By")]
        public string owner_created_by { get; set; }
        [Display(Name = "Last Modified Date")]
        [DataType(DataType.Date)]
        public DateTime owner_last_modified_date { get; set; }
        [Display(Name = "Last Modified By")]
        public string owner_last_modified_by { get; set; }
        public int owner_status { get; set; }

        public virtual ICollection<VesselOwnerRef> vessel_owner_ref { get; set; }
    }
}

DRS/Models/Vessel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DRS.Models
{
    public class Vessel
    {
        public Vessel()
        {
            this.d_detail = new HashSet<DistressViewModel>();
            this.licences = new HashSet<Licence>();
            this.vessel_owner_ref = new HashSet<VesselOwnerRef>();
        }
        public int vessel_id { get; set; }
        [Display(Name ="Vessel No")]
        [Required(ErrorMessage = "Vessel No is Required")]
        public string vessel_no { get; set; }
        [Display(Name = "Application Type")]
        [Required(ErrorMessage = "Application Type should be selected")]
        public int vessel_pending_approval { get; set; }
        [Display(Name = "Vessel Name")]
        public string vessel_name { get; set; }
        [Display(Name = "Vessel Color")]
        public string vessel_color { get; set; }
        [Display(Name = "Vessel Length Overall")]
        public string vessel_loa { get; set; }
        //common data
        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        public DateTime vessel_created_date { get; set; }
        [Display(Name = "Created By")]
        public string vessel_created_by { get; set; }
        [Display(Name = "Last Modified Date")]
        [DataType(DataType.Date)]
        public DateTime vessel_last_modified_date { get; set; }
        [Display(Name = "Last Modified By")]
        public string vessel_last_modified_by { get; set; }
        public int vessel_status { get; set; }
        [Display(Name = "Registration Code")]
        [Required(ErrorMessage = "Registration Code should be Selected")]
        public int registration_id { get; set; }
        [Display(Name = "District Code")]
        [Required(ErrorMessage = "District Code should be Selected")]
        public int district_id { get; set; }

        public virtual ICollection<DistressViewModel> d_detail { get; set; }
        public virtual District district { get; set; }
        public virtual ICollection<Licence> licences { get; set; }
        public virtual Registration registration { get; set; }
        public virtual ICollection<VesselOwnerRef> vessel_owner_ref { get; set; }
    }
}

DRS/Controllers/OwnersController.cs
using System;
using System.Web.Mvc;
using DRS.ControllerManagers.OwnersControllerManager;
using DRS.DataBase;

namespace DRS.Controllers
{
    public class OwnersController : Controller
    {
        private OwnersControllerManager OwnersControllerManager;

        public OwnersController()
        {
            OwnersControllerManager = new OwnersControllerManager();
        }

        // GET: Owners
        public ActionResult Index(string SearchType, string SearchText)
        {
            try
            {
                ViewBag.SearchOwnerType = OwnersControllerManager.getSearchOwnerTypeSelectList();
                if (SearchType != null && SearchType.Length != 0)
                {
                    return View(OwnersControllerManager.getAllOwners(SearchType, SearchText));
                }
                else
                {
                    return View(OwnersControllerManager.getOwnersICollection());
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Owners/Index" });
            }
        }

        // GTE: Owners/Details/1
        public ActionResult Details(int id)
        {
            try
            {
                return View(OwnersControllerManager.getOwner(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Owners/Details/int" });
            }
        }

        // GTE: Owners/Vessels/5
        public ActionResult Vessels(int id)
        {
            try
            {
                return View(OwnersControllerManager.getAllVessels(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Owners/Vessels/int" });
            }
        }

        // GET: Owners/MultipleVessels/5
        public ActionResult MultipleVessels(int id)
        {
            try
            {
                ViewBag.Registration = OwnersControllerManager.getRegistrationSelectList();
                ViewBag.Districts = OwnersControllerManager.getDistrictsSelectList();
                ViewBag.Applications = OwnersControllerManager.getApplicationSelectList();
                return View(OwnersControllerManager.getOwnerOnly(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Owners/MultipleVessels/int" });
            }
        }

        // POST: Owners/MultipleVessels
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MultipleVessels(vessel_owner_ref vessel_owner_ref)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int status = OwnersControllerManager.saveMultipleVessel(vessel_owner_ref);
                    if (status == 1)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["vessel_no"] = "This Vessel is already assign for this owner";
                        ViewBag.Registration = OwnersControllerManager.getRegistrationSelectList();
                        ViewBag.Districts = OwnersControllerManager.getDistrictsSelectList();
                        ViewBag.Applications = OwnersControllerManager.getApplicationSelectList();
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Owners/MultipleVessels" });
            }
        }

        // GET: Owners/Edit/1
        public ActionResult Edit(int id)
        {
            try
            {
                return View(OwnersControllerManager.getOwner(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Owners/Edit/int" });
            }
        }

        // POST: Owners/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, owner owner)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int status = OwnersControllerManager.updateOwner(id, owner);
                    if (status == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Owners/Edit/int" });
            }
        }

        // GTE: Owners/Delete/1
        public ActionResult Delete(int id)
        {
            try
            {
                return View(OwnersControllerManager.getOwner(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Owners/Delete/int" });
            }
        }

        // POST: Owners/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            try
            {
                int status = OwnersControllerManager.deleteOwner(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Owners/DeletePost/int" });
            }
        }
    }
}

DRS/Controllers/VesselsController.cs
using System;
using System.Web.Mvc;
using DRS.ControllerManagers.VesselsControllerManager;
using DRS.DataBase;

namespace DRS.Controllers
{
    public class VesselsController : Controller
    {
        private VesselsControllerManager VesselsControllerManager;

        public VesselsController()
        {
            VesselsControllerManager = new VesselsControllerManager();
        }

        [Authorize(Roles ="Admin,Officer")]
        // GET: Vessels
        public ActionResult Index(string SearchText)
        {
           try
            {
                return View(VesselsControllerManager.getAllIMULAVessels(SearchText));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/Index" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        // GET: Vessels/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return View(VesselsControllerManager.getVessel(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/Details/int" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //GET: Vessels/Owners
        public ActionResult Owners(int id)
        {
            try
            {
                return View(VesselsControllerManager.getAllOwnersOfTheVessels(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/Owners" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //GET: Vessels/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.Registration = VesselsControllerManager.getRegistrationSelectList();
                ViewBag.Districts = VesselsControllerManager.getDistrictsSelectList();
                ViewBag.Applications = VesselsControllerManager.getApplicationSelectList();
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/Create" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //POST: Vessels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(vessel_owner_ref vessel_owner_ref)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int status = VesselsControllerManager.saveVessel(vessel_owner_ref);
                    if (status == 1)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["vessel_no"] = "This Vessel is already taken";
                        ViewBag.Registration = VesselsControllerManager.getRegistrationSelectList();
                        ViewBag.Districts = VesselsControllerManager.getDistrictsSelectList();
                        ViewBag.Applications = VesselsControllerManager.getApplicationSelectList();
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Vessels/Create" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //GET: Vessels/SharedOwnership
        public ActionResult SharedOwnership(int id)
        {
            try
            {
                return View(VesselsControllerManager.getVesselOnly(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/SharedOwnership" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //POST: Vessels/SharedOwnership
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SharedOwnership(vessel_owner_ref vessel_owner_ref)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int status = VesselsControllerManager.saveSharedOwnership(vessel_owner_ref);
                    if (status == 1)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["owner_nic"] = "This Owner is already assign for this vessel";
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Vessels/SharedOwnership" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //GET: Vessel/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                ViewBag.Registration = VesselsControllerManager.getRegistrationSelectList();
                ViewBag.Districts = VesselsControllerManager.getDistrictsSelectList();
                ViewBag.Applications = VesselsControllerManager.getApplicationSelectList();
                return View(VesselsControllerManager.getVessel(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/Edit/int" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        //POST: Vessel/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, vessel vessel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int status = VesselsControllerManager.updateVessel(id, vessel);
                    if (status == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.Registration = VesselsControllerManager.getRegistrationSelectList();
                ViewBag.Districts = VesselsControllerManager.getDistrictsSelectList();
                ViewBag.Applications = VesselsControllerManager.getApplicationSelectList();

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Vessels/Edit/int" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        // GET: Vessels/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                return View(VesselsControllerManager.getVessel(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Vessels/Delete/int" });
            }
        }

        [Authorize(Roles = "Admin,Officer")]
        // POST: Vessels/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            try
            {
                int status = VesselsControllerManager.deleteVessel(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/Vessels/DeletePost/int" });
            }
        }
    }
}

DRS/Views/Vessels/Create.cshtml
@model DRS.DataBase.vessel_owner_ref

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vessel</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        @if (TempData["vessel_no"] != null)
        {
            <p style="color:red">@TempData["vessel_no"]</p>
        }

        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.registration.registration_code, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.DropDownListFor(model => model.vessel.registration_id, (SelectList)ViewBag.Registration, "Select Code", htmlAttributes: new { @class = "form-control"})
                </td>

                <td>
                    @Html.LabelFor(model => model.owner.owner_name, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.EditorFor(model => model.owner.owner_name, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.vessel_no, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    @Html.EditorFor(model => model.vessel.vessel_no, new { htmlAttributes = new { @class = "form-control" , @id = "vessel_no_digits" } })
                </td>
                <td>
                    @Html.LabelFor(model => model.owner.owner_address, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.EditorFor(model => model.owner.owner_address, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.district.district_code, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.DropDownListFor(model => model.vessel.district_id, (SelectList)ViewBag.Districts, "Select Code", htmlAttributes: new { @class = "form-control" })
                </td>
                <td>
                    @Html.LabelFor(model => model.owner.owner_tele, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.EditorFor(model => model.owner.owner_tele, new { htmlAttributes = new { @class = "form-control", @id = "telephone" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.vessel_pending_approval, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.DropDownListFor(model => model.vessel.vessel_pending_approval, (SelectList)ViewBag.Applications, "Select Type", htmlAttributes: new { @class = "form-control" })
                </td>
                <td>
                    @Html.LabelFor(model => model.owner.owner_nic, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    <p></p>@Html.EditorFor(model => model.owner.owner_nic, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.vessel_name, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    @Html.EditorFor(model => model.vessel.vessel_name, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.vessel_color, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    @Html.EditorFor(model => model.vessel.vessel_color, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.vessel.vessel_loa, htmlAttributes: new { @class = "control-label col-md-12" })
                </td>
                <td>
                    @Html.EditorFor(model => model.vessel.vessel_loa, new { htmlAttributes = new { @class = "form-control", @id = "vessel_loa" } })
                </td>
            </tr>
            <tr><td><br /><td></tr>


            <tr>
                <td>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </div>
                </td>
            </tr>
        </table>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/Scripts/jquery.maskedinput.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $("#vessel_no_digits").mask("9999");
        });

        $(function () {
            $("#vessel_loa").mask("ft:999 inch:99");
        });

        $(function () {
            $("#telephone").mask("9999999999");
        });
    </script>

}

DRS/Views/Vessels/Delete.cshtml
@model DRS.DataBase.vessel_owner_ref

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vessel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.registration.registration_code)
            @Html.DisplayFor(model => model.vessel.vessel_no)
            @Html.DisplayFor(model => model.vessel.district.district_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_loa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_loa)
        </dd>
    </dl>

    <br />
    <h4>Record Details</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_last_modified_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_last_modified_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_last_modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_last_modified_by)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.vessel.vessel_id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DRS/Views/Vessels/Details.cshtml
@model DRS.DataBase.vessel_owner_ref

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Vessel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.registration.registration_code)
            @Html.DisplayFor(model => model.vessel.vessel_no)
            @Html.DisplayFor(model => model.vessel.district.district_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_loa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_loa)
        </dd>
    </dl>

    <br />
    <h4>Record Details</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_last_modified_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_last_modified_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vessel.vessel_last_modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vessel.vessel_last_modified_by)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "Vessels", new { id = Model.vessel_id }, htmlAttributes: new { @class = "btn btn-warning" })
</p>

DRS/Views/Vessels/Index.cshtml
@model IEnumerable<DRS.DataBase.vessel>

@using GridMvc.Html
@{
    ViewBag.Title = "Index";  
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vessels</h2>

<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

<p>
    @Html.ActionLink("Create New", "Create", "Vessels", htmlAttributes: new { @class = "btn btn-success btn-primary btn-sm" })
</p>

<table>
    <tr>
        <td>
            <span style="margin:320px"></span>
            <div class="search-bar">
                @using (Html.BeginForm("Index", "Vessels", FormMethod.Get))
                {
                    <table>
                        <tr>
                            <td>
                                @if (Context.User.IsInRole("Admin"))
                                {
                                    @Html.TextBox("SearchText", "", new { @class = "form-control", @id = "vessel_no" })
                                }
                                else
                                {
                                    @Html.TextBox("SearchText", "", new { @class = "form-control", @id = "vessel_no_imul" })
                                }
                            </td>
                            <td>
                                <span style="margin:5px"></span>
                                <input type="submit" value="Search" class="btn btn-info btn-primary btn-sm" />
                            </td>
                        </tr>
                    </table>
                }
            </div>
        </td>
    </tr>
</table>

<div class="code-cut">
    @Html.Grid(Model).Columns(Columns =>
{
Columns.Add(c => c.registration.registration_code).Titled("Registration").Filterable(true);
Columns.Add(c => c.vessel_no).Titled("Vessel No").Filterable(true);
Columns.Add(c => c.district.district_code).Titled("District").Filterable(true);

    Columns.Add()
        .Titled("")
        .SetWidth(15)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => @Html.ActionLink("Add", "SharedOwnership", "Vessels", new { id = c.vessel_id }, htmlAttributes: new { @class = "btn btn-success btn-primary btn-sm" }));
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Owners", "Owners", "Vessels", new { id = c.vessel_id }, htmlAttributes: new { @class = "btn btn-success btn-primary btn-sm" }));
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Edit", "Edit", "Vessels", new { id = c.vessel_id }, htmlAttributes: new { @class = "btn btn-warning btn-primary btn-sm" }));
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Details", "Details", "Vessels", new { id = c.vessel_id }, htmlAttributes: new { @class = "btn btn-info btn-primary btn-sm" }));
    Columns.Add()
        .Titled("")
        .SetWidth(10)
        .Filterable(true)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(c => Html.ActionLink("Delete", "Delete", "Vessels", new { id = c.vessel_id }, htmlAttributes: new { @class = "btn btn-danger btn-primary btn-sm" }));

}).WithPaging(10).Sortable().Filterable()
</div>

@section Scripts{
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/Scripts/jquery.maskedinput.min.js"></script>

    <script type="text/javascript">
        $.mask.definitions['D'] = "[/^A-Z*/]";   //District must only accept English letters
        $(function () {
            $("#vessel_no").mask("DDDD-A-9999DDD");
            $("#vessel_no_imul").mask("IMUL-A-9999DDD");
        });
    </script>
}