DRS/Models/RadioStation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DRS.Models
{
    public class RadioStation
    {
        public RadioStation()
        {
            this.d_detail = new HashSet<DistressViewModel>();
            this.users = new HashSet<User>();
        }
        public int mcs_id { get; set; }
        [Display(Name = "MCS Callsign")]
        [Required(ErrorMessage = "MCS Callsign is Required")]
        public string mcs_callsign { get; set; }
        [Display(Name = "MCS Center Location")]
        [Required(ErrorMessage = "MCS Center Location is Required")]
        public string mcs_location { get; set; }
        [Display(Name = "Current Radio Type")]
        [Required(ErrorMessage = "Current Radio Type is Required")]
        public string mcs_radio_equipment { get; set; }
        [Display(Name = "Radio placed Date")]
        [Required(ErrorMessage = "Radio placed Date is Required")]
        [DataType(DataType.Date)]
        public DateTime mcs_radio_equipment_place_date { get; set; }
        //common data
        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        public DateTime mcs_created_date { get; set; }
        [Display(Name = "Created By")]
        public string mcs_created_by { get; set; }
        [Display(Name = "Last Modified Date")]
        [DataType(DataType.Date)]
        public DateTime mcs_last_modified_date { get; set; }
        [Display(Name = "Last Modified By")]
        public string mcs_last_modified_by { get; set; }
        public int mcs_status { get; set; }

        public virtual ICollection<DistressViewModel> d_detail { get; set; }
        public virtual ICollection<User> users { get; set; }
    }
}

DRS/Controllers/RadioStationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DRS.ControllerManagers.RadioStationControllerManager;
using DRS.DataBase;

namespace DRS.Controllers
{
    public class RadioStationsController : Controller
    {
        private RadioStationsControllerManager RadioStationsControllerManager;

        public RadioStationsController()
        {
            RadioStationsControllerManager = new RadioStationsControllerManager();
        }

        [Authorize(Roles = "Admin,User")]
        // GET: RadioStations
        public ActionResult Index()
        {
            try
            {
                return View(RadioStationsControllerManager.getAllRadioStations());
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/RadioStations/Index" });
            }
        }

        [Authorize(Roles = "Admin,User")]
        // GET: RadioStations/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return View(RadioStationsControllerManager.getRadioStation(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/RadioStations/Details/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: RadioStations/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/RadioStations/Create" });
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: RadioStations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(radio_station radio_station)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int flag = RadioStationsControllerManager.saveRadioStation(radio_station);
                    if (flag == 1)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["mcs_callsign"] = "This MCS Center Callsign is already taken";
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/RadioStations/Create" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: RadioStations/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                return View(RadioStationsControllerManager.getRadioStation(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/Edit/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: RadioStations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, radio_station radio_station)
        {
            try
            {
                int flag = RadioStationsControllerManager.updateRadioStation(id, radio_station);
                if (flag == 1)
                {
                    return RedirectToAction("Index");
                }
                else
                    return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/RadioStations/Edit/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: RadioStations/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                return View(RadioStationsControllerManager.getRadioStation(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "GET/RadioStations/Delete/int" });
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: RadioStations/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, radio_station radio_station)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RadioStationsControllerManager.deleteRadioStation(id, radio_station);
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { error = "POST/RadioStations/Delete/int" });
            }
        }
    }
}

DRS/Views/RadioStations/Create.cshtml
@model DRS.DataBase.radio_station

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MCS Center</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (TempData["mcs_callsign"] != null)
        {
        <p style="color:red">@TempData["mcs_callsign"]</p>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_callsign, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_callsign, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_callsign, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_radio_equipment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_radio_equipment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_radio_equipment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_radio_equipment_place_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_radio_equipment_place_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_radio_equipment_place_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DRS/Views/RadioStations/Delete.cshtml
@model DRS.DataBase.radio_station

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MCS Center</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mcs_location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_callsign)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_callsign)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_radio_equipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_radio_equipment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_radio_equipment_place_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_radio_equipment_place_date)
        </dd>
    </dl>

    <br />
    <h4>Record Details</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mcs_created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_last_modified_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_last_modified_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_last_modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_last_modified_by)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.mcs_id)
        @Html.HiddenFor(model => model.mcs_location)
        @Html.HiddenFor(model => model.mcs_callsign)
        @Html.HiddenFor(model => model.mcs_radio_equipment)
        @Html.HiddenFor(model => model.mcs_radio_equipment_place_date)
        @Html.HiddenFor(model => model.mcs_created_date)
        @Html.HiddenFor(model => model.mcs_created_by)
        @Html.HiddenFor(model => model.mcs_status)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

DRS/Views/RadioStations/Details.cshtml
@model DRS.DataBase.radio_station

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MCS Center</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mcs_location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_callsign)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_callsign)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_radio_equipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_radio_equipment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_radio_equipment_place_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_radio_equipment_place_date)
        </dd>
    </dl>

    <br />
    <h4>Record Details.</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mcs_created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_last_modified_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_last_modified_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mcs_last_modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mcs_last_modified_by)
        </dd>

    </dl>
</div>

@if (Request.IsAuthenticated)
{
    if (Context.User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.mcs_id }, htmlAttributes: new { @class = "btn btn-warning" })
        </p>

    }
}

DRS/Views/RadioStations/Edit.cshtml
@model DRS.DataBase.radio_station

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MCS Center</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.mcs_id)
        @Html.HiddenFor(model => model.mcs_callsign)
        @Html.HiddenFor(model => model.mcs_created_by)
        @Html.HiddenFor(model => model.mcs_created_date)
        @Html.HiddenFor(model => model.mcs_status)

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_radio_equipment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_radio_equipment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_radio_equipment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mcs_radio_equipment_place_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mcs_radio_equipment_place_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mcs_radio_equipment_place_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DRS/Views/RadioStations/Index.cshtml
@model IEnumerable<DRS.DataBase.radio_station>
@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MCS Centers</h2>

<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

@if (Request.IsAuthenticated)
{
    if (Context.User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Create New", "Create", "RadioStations", htmlAttributes: new { @class = "btn btn-success btn-primary btn-sm" })
        </p>
    }
}

<div class="code-cut">
    @Html.Grid(Model).Columns(Columns =>
{
    Columns.Add(c => c.mcs_location).Titled("MCS Center Location").Filterable(true);
    Columns.Add(c => c.mcs_callsign).Titled("Callsign").Filterable(true);
    Columns.Add(c => c.mcs_radio_equipment).Titled("Radio Equipment").Filterable(true);
    Columns.Add(c => c.mcs_radio_equipment_place_date).Titled("Radio Equipment Place Date").Filterable(true);

    if (Request.IsAuthenticated)
    {
        if (Context.User.IsInRole("Admin"))
        {
            Columns.Add()
                .Titled("")
                .SetWidth(10)
                .Filterable(true)
                .Sanitized(false)
                .Encoded(false)
                .RenderValueAs(c => Html.ActionLink("Edit", "Edit", "RadioStations", new { id = c.mcs_id }, htmlAttributes: new { @class = "btn btn-warning btn-primary btn-sm" })
                .ToHtmlString());
            Columns.Add()
                .Titled("")
                .SetWidth(10)
                .Filterable(true)
                .Sanitized(false)
                .Encoded(false)
                .RenderValueAs(c => Html.ActionLink("Details", "Details", "RadioStations", new { id = c.mcs_id }, htmlAttributes: new { @class = "btn btn-info btn-primary btn-sm" })
                .ToHtmlString());
            Columns.Add()
                .Titled("")
                .SetWidth(10)
                .Filterable(true)
                .Sanitized(false)
                .Encoded(false)
                .RenderValueAs(c => Html.ActionLink("Delete", "Delete", "RadioStations", new { id = c.mcs_id }, htmlAttributes: new { @class = "btn btn-danger btn-primary btn-sm" })
                .ToHtmlString());
        }

        else
        {
            Columns.Add()
                .Titled("")
                .SetWidth(10)
                .Filterable(true)
                .Sanitized(false)
                .Encoded(false)
                .RenderValueAs(c => Html.ActionLink("Details", "Details", "RadioStations", new { id = c.mcs_id }, htmlAttributes: new { @class = "btn btn-info btn-primary btn-sm" })
                .ToHtmlString());
        }
    }


}).WithPaging(10).Sortable().Filterable()
</div>